### ISSUE TITLE
Request for information form

### ISSUE THREAD

**Issue by zanesensenig** [open-curriculum/program-hub#26]
We should come up with a solution for the request for information form located on the landing page.

**Comment by michael-collins** [comment]
This should package up the info and email someone at WC. Need something that prevents spammers and robots.

**Comment by michael-collins** [comment]
@mmilutinovic1313 This would be a good thing to tackle when you get a chance.

**Comment by mmilutinovic013** [comment]
Will do --

**Comment by mmilutinovic013** [comment]
Update: Got the "I am not a robot button working" Wondering how to hide the site API key before pushing to github.

**Comment by michael-collins** [comment]
@mmilutinovic1313 does it need to be hidden? Are the keys seeable when the sites are published anyway?

**Comment by mmilutinovic013** [comment]
It would be visible in the repo itself since it's in the code: 

 `<div class="g-recaptcha" data-sitekey="example-key"></div>`

**Comment by mmilutinovic013** [comment]
I can ask Bryan what he has done in the path to deal with API keys

**Comment by michael-collins** [comment]
Sounds good.

**Comment by mmilutinovic013** [comment]
Okay making a var file to add to gitignore

**Comment by mmilutinovic1313** [comment]
Update: I can get the recaptcha to print to the page, however since we don't have backend validation such as PHP we cannot verify or require the "I am not a robot" button. I have looked through stackoverflow and people seem to like simpleform to do validation in jekyll  https://getsimpleform.com/. I need to research it / other options a bit more

**Comment by mmilutinovic013** [comment]
https://formspree.io/
